# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hbi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hbi.proto',
  package='hostinventory',
  syntax='proto3',
  serialized_pb=_b('\n\thbi.proto\x12\rhostinventory\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n\x04UUID\x12\r\n\x05value\x18\x01 \x01(\t\"5\n\x04\x46\x61\x63t\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"5\n\x03Tag\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x8b\x02\n\x04Host\x12\x1f\n\x02id\x18\x01 \x01(\x0b\x32\x13.hostinventory.UUID\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\"\n\x05\x66\x61\x63ts\x18\x03 \x03(\x0b\x32\x13.hostinventory.Fact\x12,\n\x0f\x63\x61nonical_facts\x18\x04 \x03(\x0b\x32\x13.hostinventory.Fact\x12 \n\x04tags\x18\x05 \x03(\x0b\x32\x12.hostinventory.Tag\x12+\n\x07\x63reated\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\".\n\x08HostList\x12\"\n\x05hosts\x18\x01 \x03(\x0b\x32\x13.hostinventory.Host\"p\n\x06\x46ilter\x12 \n\x03ids\x18\x01 \x03(\x0b\x32\x13.hostinventory.UUID\x12\"\n\x05\x66\x61\x63ts\x18\x02 \x03(\x0b\x32\x13.hostinventory.Fact\x12 \n\x04tags\x18\x03 \x03(\x0b\x32\x12.hostinventory.Tag2\xea\x01\n\rHostInventory\x12\x34\n\x06\x43reate\x12\x13.hostinventory.Host\x1a\x13.hostinventory.Host\"\x00\x12\x34\n\x06Update\x12\x13.hostinventory.Host\x1a\x13.hostinventory.Host\"\x00\x12\x37\n\x03Get\x12\x15.hostinventory.Filter\x1a\x17.hostinventory.HostList\"\x00\x12\x34\n\x06\x44\x65lete\x12\x13.hostinventory.Host\x1a\x13.hostinventory.Host\"\x00\x42;\n\x1d\x63om.redhat.insights.inventoryB\x12HostInventoryProtoP\x01\xa2\x02\x03HBIb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='hostinventory.UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='hostinventory.UUID.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=82,
)


_FACT = _descriptor.Descriptor(
  name='Fact',
  full_name='hostinventory.Fact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='hostinventory.Fact.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='hostinventory.Fact.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hostinventory.Fact.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=137,
)


_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='hostinventory.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='hostinventory.Tag.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='hostinventory.Tag.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hostinventory.Tag.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=192,
)


_HOST = _descriptor.Descriptor(
  name='Host',
  full_name='hostinventory.Host',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hostinventory.Host.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='hostinventory.Host.display_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='facts', full_name='hostinventory.Host.facts', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canonical_facts', full_name='hostinventory.Host.canonical_facts', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='hostinventory.Host.tags', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='hostinventory.Host.created', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated', full_name='hostinventory.Host.updated', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=462,
)


_HOSTLIST = _descriptor.Descriptor(
  name='HostList',
  full_name='hostinventory.HostList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hosts', full_name='hostinventory.HostList.hosts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=510,
)


_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='hostinventory.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='hostinventory.Filter.ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='facts', full_name='hostinventory.Filter.facts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='hostinventory.Filter.tags', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=624,
)

_HOST.fields_by_name['id'].message_type = _UUID
_HOST.fields_by_name['facts'].message_type = _FACT
_HOST.fields_by_name['canonical_facts'].message_type = _FACT
_HOST.fields_by_name['tags'].message_type = _TAG
_HOST.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_HOST.fields_by_name['updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_HOSTLIST.fields_by_name['hosts'].message_type = _HOST
_FILTER.fields_by_name['ids'].message_type = _UUID
_FILTER.fields_by_name['facts'].message_type = _FACT
_FILTER.fields_by_name['tags'].message_type = _TAG
DESCRIPTOR.message_types_by_name['UUID'] = _UUID
DESCRIPTOR.message_types_by_name['Fact'] = _FACT
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['Host'] = _HOST
DESCRIPTOR.message_types_by_name['HostList'] = _HOSTLIST
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), dict(
  DESCRIPTOR = _UUID,
  __module__ = 'hbi_pb2'
  # @@protoc_insertion_point(class_scope:hostinventory.UUID)
  ))
_sym_db.RegisterMessage(UUID)

Fact = _reflection.GeneratedProtocolMessageType('Fact', (_message.Message,), dict(
  DESCRIPTOR = _FACT,
  __module__ = 'hbi_pb2'
  # @@protoc_insertion_point(class_scope:hostinventory.Fact)
  ))
_sym_db.RegisterMessage(Fact)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'hbi_pb2'
  # @@protoc_insertion_point(class_scope:hostinventory.Tag)
  ))
_sym_db.RegisterMessage(Tag)

Host = _reflection.GeneratedProtocolMessageType('Host', (_message.Message,), dict(
  DESCRIPTOR = _HOST,
  __module__ = 'hbi_pb2'
  # @@protoc_insertion_point(class_scope:hostinventory.Host)
  ))
_sym_db.RegisterMessage(Host)

HostList = _reflection.GeneratedProtocolMessageType('HostList', (_message.Message,), dict(
  DESCRIPTOR = _HOSTLIST,
  __module__ = 'hbi_pb2'
  # @@protoc_insertion_point(class_scope:hostinventory.HostList)
  ))
_sym_db.RegisterMessage(HostList)

Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), dict(
  DESCRIPTOR = _FILTER,
  __module__ = 'hbi_pb2'
  # @@protoc_insertion_point(class_scope:hostinventory.Filter)
  ))
_sym_db.RegisterMessage(Filter)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\035com.redhat.insights.inventoryB\022HostInventoryProtoP\001\242\002\003HBI'))

_HOSTINVENTORY = _descriptor.ServiceDescriptor(
  name='HostInventory',
  full_name='hostinventory.HostInventory',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=627,
  serialized_end=861,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='hostinventory.HostInventory.Create',
    index=0,
    containing_service=None,
    input_type=_HOST,
    output_type=_HOST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='hostinventory.HostInventory.Update',
    index=1,
    containing_service=None,
    input_type=_HOST,
    output_type=_HOST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='hostinventory.HostInventory.Get',
    index=2,
    containing_service=None,
    input_type=_FILTER,
    output_type=_HOSTLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='hostinventory.HostInventory.Delete',
    index=3,
    containing_service=None,
    input_type=_HOST,
    output_type=_HOST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HOSTINVENTORY)

DESCRIPTOR.services_by_name['HostInventory'] = _HOSTINVENTORY

# @@protoc_insertion_point(module_scope)
