# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hbi_pb2 as hbi__pb2


class HostInventoryStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/hostinventory.HostInventory/Create',
        request_serializer=hbi__pb2.Host.SerializeToString,
        response_deserializer=hbi__pb2.Host.FromString,
        )
    self.Update = channel.unary_unary(
        '/hostinventory.HostInventory/Update',
        request_serializer=hbi__pb2.Host.SerializeToString,
        response_deserializer=hbi__pb2.Host.FromString,
        )
    self.Get = channel.unary_unary(
        '/hostinventory.HostInventory/Get',
        request_serializer=hbi__pb2.Filter.SerializeToString,
        response_deserializer=hbi__pb2.HostList.FromString,
        )
    self.Delete = channel.unary_unary(
        '/hostinventory.HostInventory/Delete',
        request_serializer=hbi__pb2.Host.SerializeToString,
        response_deserializer=hbi__pb2.Host.FromString,
        )


class HostInventoryServicer(object):
  """Interface exported by the server.
  """

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HostInventoryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=hbi__pb2.Host.FromString,
          response_serializer=hbi__pb2.Host.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=hbi__pb2.Host.FromString,
          response_serializer=hbi__pb2.Host.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=hbi__pb2.Filter.FromString,
          response_serializer=hbi__pb2.HostList.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=hbi__pb2.Host.FromString,
          response_serializer=hbi__pb2.Host.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hostinventory.HostInventory', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
